# SPDX-License-Identifier: GPL-2.0-only
# Copyright 2016 Stephan Linz <linz@li-pro.net>

language: c

matrix:
    include:
        - os: linux
          dist: trusty
          sudo: required
          compiler: gcc
        - os: linux
          dist: trusty
          sudo: required
          compiler: clang

addons:
    apt:
        packages:
            - meson
            - libudev-dev
            - libusb-dev
            - libusb-1.0-0-dev
        sources:
            - ubuntu-toolchain-r-test

script:
    - ./autogen.sh
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./travis-autogen.sh && make -j4; fi
